Arcade: IGame Class Reference
IGame Class Reference abstract
#include <IGame.hpp>
Public Member Functions
IGame ()=default
virtual ~IGame ()=default
virtual void init (IGraphical *graphics, std::string playerName)=0
Initialize the game.
virtual void update ()=0
Update the game each frame.
virtual void handleInput (Input input)=0
Handle the input of the player.
virtual void render ()=0
Render the game.
virtual std::string getName () const =0
Get the Name of the game.
virtual unsigned int getCurrentScore () const =0
Get the Current Score of the game.
virtual unsigned int getHighScore () const =0
Get the High Score of the game.
virtual void setState (GameState state)=0
Set the State of the game.
virtual GameState getState () const =0
Get the State of the game.
Protected Attributes
GameState _state = GameState::PAUSED
unsigned int _currentScore
unsigned int _highScore
std::unordered_map< std::string, unsigned int > _highScores
std::string _playerName
IGraphical * _graphical
Detailed Description
Definition at line 31 of file IGame.hpp.
Constructor & Destructor Documentation
IGame()
IGame::IGame () default
~IGame()
virtual IGame::~IGame () virtual default
Member Function Documentation
getCurrentScore()
virtual unsigned int IGame::getCurrentScore () const pure virtual
Get the Current Score of the game.
Returns
unsigned int The current score of the game
Implemented in Snake, and Nibbler.
getHighScore()
virtual unsigned int IGame::getHighScore () const pure virtual
Get the High Score of the game.
Returns
unsigned int The high score of the game
Implemented in Snake, and Nibbler.
getName()
virtual std::string IGame::getName () const pure virtual
Get the Name of the game.
Returns
std::string The name of the game
Implemented in Snake, and Nibbler.
getState()
virtual GameState IGame::getState () const pure virtual
Get the State of the game.
Returns
GameState The state of the game (RUNNING, PAUSED, GAME_OVER, WIN)
Implemented in Snake, and Nibbler.
Referenced by Arcade::Core::gameLoop().
handleInput()
virtual void IGame::handleInput (Input input) pure virtual
Handle the input of the player.
Parameters
input The input of the player
Implemented in Snake, and Nibbler.
Referenced by Arcade::Core::gameLoop().
init()
virtual void IGame::init (IGraphical * graphics, std::string playerName) pure virtual
Initialize the game.
Parameters
graphics The graphical library to use
playerName The player name of the current player
Implemented in Snake, and Nibbler.
Referenced by Arcade::Core::launchGame(), and Arcade::Core::switchLibs().
render()
virtual void IGame::render () pure virtual
Render the game.
Implemented in Snake, and Nibbler.
Referenced by Arcade::Core::gameLoop().
setState()
virtual void IGame::setState (GameState state) pure virtual
Set the State of the game.
Parameters
state The state of the game (RUNNING, PAUSED, GAME_OVER, WIN)
Implemented in Snake, and Nibbler.
Referenced by Arcade::Core::launchGame().
update()
virtual void IGame::update () pure virtual
Update the game each frame.
Implemented in Snake, and Nibbler.
Referenced by Arcade::Core::gameLoop().
Field Documentation
_currentScore
unsigned int IGame::_currentScore protected
Definition at line 93 of file IGame.hpp.
_graphical
IGraphical* IGame::_graphical protected
Definition at line 97 of file IGame.hpp.
Referenced by Nibbler::init(), Snake::init(), Nibbler::render(), and Snake::render().
_highScore
unsigned int IGame::_highScore protected
Definition at line 94 of file IGame.hpp.
_highScores
std::unordered_map<std::string, unsigned int> IGame::_highScores protected
Definition at line 95 of file IGame.hpp.
_playerName
std::string IGame::_playerName protected
Definition at line 96 of file IGame.hpp.
_state
GameState IGame::_state = GameState::PAUSED protected
Definition at line 92 of file IGame.hpp.
The documentation for this class was generated from the following file:
games/IGame.hpp