Arcade: Snake Class Reference
Snake Class Reference
#include <Snake.hpp>
Data Structures
struct Fruit
struct SnakeSegment
Public Member Functions
~Snake () override
void init (IGraphical *graphics, std::string playerName) override
Initialize the game.
void update () override
Update the game each frame.
void handleInput (Input input) override
Handle the input of the player.
void render () override
Render the game.
std::string getName () const override
Get the Name of the game.
unsigned int getCurrentScore () const override
Get the Current Score of the game.
unsigned int getHighScore () const override
Get the High Score of the game.
void setState (GameState state) override
Set the State of the game.
GameState getState () const override
Get the State of the game.
Public Member Functions inherited from IGame
IGame ()=default
virtual ~IGame ()=default
Private Member Functions
void start ()
void generateFruit ()
void updateSnake ()
bool checkCollision ()
void loadHighScores ()
void saveHighScores ()
void updateHighScore ()
void delay (int milliseconds)
Private Attributes
const int Size = 20
const int width = Size * Size
const int height = Size * Size
int num = 4
int dir = 1
bool _firstStart = true
struct Snake::SnakeSegment s [100]
struct Snake::Fruit f
unsigned int _currentScore = 0
unsigned int _highScore = 0
std::unordered_map< std::string, unsigned int > _highScores
std::string _playerName
GameState _state = GameState::PAUSED
IGraphical * _graphics
Additional Inherited Members
Protected Attributes inherited from IGame
GameState _state = GameState::PAUSED
unsigned int _currentScore
unsigned int _highScore
std::unordered_map< std::string, unsigned int > _highScores
std::string _playerName
IGraphical * _graphical
Detailed Description
Definition at line 14 of file Snake.hpp.
Constructor & Destructor Documentation
~Snake()
Snake::~Snake () inline override
Definition at line 16 of file Snake.hpp.
 {}
Member Function Documentation
checkCollision()
bool Snake::checkCollision () private
Definition at line 107 of file Snake.cpp.
{
     if (s[0].x > Size || s[0].x < 0 || s[0].y > Size || s[0].y < 0)
         return true;
     for (int i = 1; i < num; i++) {
         if (s[0].x == s[i].x && s[0].y == s[i].y) {
             return true;
         }
     }
     return false;
 }
References num, s, and Size.
Referenced by update().
delay()
void Snake::delay (int milliseconds) private
Definition at line 120 of file Snake.cpp.
{
     auto start_time = std::chrono::high_resolution_clock::now();
     while (std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now() - start_time).count() < milliseconds) {}
 }
Referenced by updateSnake().
generateFruit()
void Snake::generateFruit () private
Definition at line 84 of file Snake.cpp.
{
     f.x = rand() % Size;
     f.y = rand() % Size;
 }
References f, Size, Snake::Fruit::x, and Snake::Fruit::y.
Referenced by start(), and updateSnake().
getCurrentScore()
unsigned int Snake::getCurrentScore () const inline override virtual
Get the Current Score of the game.
Returns
unsigned int The current score of the game
Implements IGame.
Definition at line 24 of file Snake.hpp.
 { return _currentScore; }
References _currentScore.
getHighScore()
unsigned int Snake::getHighScore () const inline override virtual
Get the High Score of the game.
Returns
unsigned int The high score of the game
Implements IGame.
Definition at line 25 of file Snake.hpp.
 { return _highScore; }
References _highScore.
getName()
std::string Snake::getName () const inline override virtual
Get the Name of the game.
Returns
std::string The name of the game
Implements IGame.
Definition at line 23 of file Snake.hpp.
 { return "Snake"; }
getState()
GameState Snake::getState () const inline override virtual
Get the State of the game.
Returns
GameState The state of the game (RUNNING, PAUSED, GAME_OVER, WIN)
Implements IGame.
Definition at line 27 of file Snake.hpp.
 { return _state; }
References _state.
handleInput()
void Snake::handleInput (Input input) override virtual
Handle the input of the player.
Parameters
input The input of the player
Implements IGame.
Definition at line 42 of file Snake.cpp.
{
     if (input == Input::Z && dir != 2)
         dir = 0;
     if (input == Input::D && dir != 3)
         dir = 1;
     if (input == Input::S && dir != 0)
         dir = 2;
     if (input == Input::Q && dir != 1)
         dir = 3;
     if (input == Input::SPACE) {
         _state = GameState::RUNNING;
         _currentScore = 0;
         num = 4;
         dir = 1;
         for (int i = 1; i < num; i++) {
             s[i].x = 10;
             s[i].y = 10;
         }
         start();
     }
     if (input == Input::BACKSPACE)
         _state = GameState::GAME_OVER;
 }
References _currentScore, _state, BACKSPACE, D, dir, GAME_OVER, num, Q, RUNNING, S, s, SPACE, start(), Snake::SnakeSegment::x, Snake::SnakeSegment::y, and Z.
init()
void Snake::init (IGraphical * graphics, std::string playerName) override virtual
Initialize the game.
Parameters
graphics The graphical library to use
playerName The player name of the current player
Implements IGame.
Definition at line 10 of file Snake.cpp.
{
     _graphical = graphics;
     _playerName = playerName;
     loadHighScores();
     if (_firstStart)
         start();
 }
References _firstStart, IGame::_graphical, _playerName, loadHighScores(), and start().
loadHighScores()
void Snake::loadHighScores () private
Definition at line 140 of file Snake.cpp.
{
     std::ifstream file(SNAKE_HIGHSCORES_FILE);
     if (file.is_open()) {
         std::string line;
         while (std::getline(file, line)) {
             std::stringstream ss(line);
             std::string playerName;
             unsigned int highScore;
             ss >> playerName >> highScore;
             _highScores[playerName] = highScore;
         }
         file.close();
     }
     else {
         saveHighScores();
     }
     if (_highScores.find(_playerName) != _highScores.end()) {
         _highScore = _highScores[_playerName];
     }
 }
References _highScore, _highScores, _playerName, saveHighScores(), and SNAKE_HIGHSCORES_FILE.
Referenced by init().
render()
void Snake::render () override virtual
Render the game.
Implements IGame.
Definition at line 66 of file Snake.cpp.
                    {
     _graphical->drawRectangle(Vector2f(START_WIN_X - Size, START_WIN_Y - Size), Vector2f(WIN_X + Size + (Size * 2), WIN_X + Size + (Size * 2)), Color::WHITE);
     for (int i = 0; i < num; i++) {
         _graphical->drawRectangle(Vector2f(s[i].x * Size + START_WIN_X, s[i].y * Size + START_WIN_Y), Vector2f(20, 20), Color::GREEN);
         _graphical->drawRectangle(Vector2f(s[0].x * Size + START_WIN_X, s[0].y * Size + START_WIN_Y), Vector2f(20, 20), Color::BLUE);
     }
     _graphical->drawText(Vector2f(START_WIN_X + 500, START_WIN_Y + 100), "High Scores :", 16, Color::WHITE);
     int i = 0;
     for (auto& entry : _highScores) {
         _graphical->drawText(Vector2f(START_WIN_X + 500, START_WIN_Y + 150 + (i * 20)), entry.first + " : " + std::to_string(entry.second), 16, Color::WHITE);
         i++;
     }
     _graphical->drawText(Vector2f(START_WIN_X + 150, START_WIN_Y - 100), "Current Score : " + std::to_string(_currentScore), 18, Color::WHITE);
     _graphical->drawRectangle(Vector2f(f.x * Size + START_WIN_X, f.y * Size + START_WIN_Y), Vector2f(20, 20), Color::RED);
 }
References _currentScore, IGame::_graphical, _highScores, BLUE, IGraphical::drawRectangle(), IGraphical::drawText(), f, GREEN, num, RED, s, Size, START_WIN_X, START_WIN_Y, WHITE, WIN_X, Snake::Fruit::x, and Snake::Fruit::y.
saveHighScores()
void Snake::saveHighScores () private
Definition at line 128 of file Snake.cpp.
{
     std::ofstream file(SNAKE_HIGHSCORES_FILE);
     if (file.is_open()) {
         for (auto& entry : _highScores) {
             file << entry.first << " " << entry.second << std::endl;
         }
         file.close();
     }
 }
References _highScores, and SNAKE_HIGHSCORES_FILE.
Referenced by loadHighScores(), and updateHighScore().
setState()
void Snake::setState (GameState state) inline override virtual
Set the State of the game.
Parameters
state The state of the game (RUNNING, PAUSED, GAME_OVER, WIN)
Implements IGame.
Definition at line 26 of file Snake.hpp.
 { _state = state; }
References _state.
start()
void Snake::start () private
Definition at line 20 of file Snake.cpp.
                   {
     srand(time(nullptr));
     s[0].x = 10;
     s[0].y = 10;
     generateFruit();
     _firstStart = false;
 }
References _firstStart, generateFruit(), s, Snake::SnakeSegment::x, and Snake::SnakeSegment::y.
Referenced by handleInput(), and init().
update()
void Snake::update () override virtual
Update the game each frame.
Implements IGame.
Definition at line 30 of file Snake.cpp.
                    {
     if (_state == GameState::RUNNING) {
         updateSnake();
         _currentScore = num - 4;
         if (checkCollision()) {
             _state = GameState::GAME_OVER;
             updateHighScore();
         }
     }
 }
References _currentScore, _state, checkCollision(), GAME_OVER, num, RUNNING, updateHighScore(), and updateSnake().
updateHighScore()
void Snake::updateHighScore () private
Definition at line 164 of file Snake.cpp.
{
     if (_currentScore > _highScore) {
         _highScore = _currentScore;
         _highScores[_playerName] = _highScore;
         saveHighScores();
     }
 }
References _currentScore, _highScore, _highScores, _playerName, and saveHighScores().
Referenced by update().
updateSnake()
void Snake::updateSnake () private
Definition at line 89 of file Snake.cpp.
{
     for (int i = num - 1; i > 0; --i) {
         s[i].x = s[i - 1].x;
         s[i].y = s[i - 1].y;
     }
     if (dir == 0) s[0].y -= 1;
     if (dir == 1) s[0].x += 1;
     if (dir == 2) s[0].y += 1;
     if (dir == 3) s[0].x -= 1;
     if ((s[0].x == f.x) && (s[0].y == f.y)) {
         num++;
         generateFruit();
     }
     delay(100);
 }
References delay(), dir, f, generateFruit(), num, s, Snake::SnakeSegment::x, Snake::Fruit::x, Snake::SnakeSegment::y, and Snake::Fruit::y.
Referenced by update().
Field Documentation
_currentScore
unsigned int Snake::_currentScore = 0 private
Definition at line 45 of file Snake.hpp.
Referenced by getCurrentScore(), handleInput(), render(), update(), and updateHighScore().
_firstStart
bool Snake::_firstStart = true private
Definition at line 35 of file Snake.hpp.
Referenced by init(), and start().
_graphics
IGraphical* Snake::_graphics private
Definition at line 51 of file Snake.hpp.
_highScore
unsigned int Snake::_highScore = 0 private
Definition at line 46 of file Snake.hpp.
Referenced by getHighScore(), loadHighScores(), and updateHighScore().
_highScores
std::unordered_map<std::string, unsigned int> Snake::_highScores private
Definition at line 47 of file Snake.hpp.
Referenced by loadHighScores(), render(), saveHighScores(), and updateHighScore().
_playerName
std::string Snake::_playerName private
Definition at line 48 of file Snake.hpp.
Referenced by init(), loadHighScores(), and updateHighScore().
_state
GameState Snake::_state = GameState::PAUSED private
Definition at line 49 of file Snake.hpp.
Referenced by getState(), handleInput(), setState(), and update().
dir
int Snake::dir = 1 private
Definition at line 34 of file Snake.hpp.
Referenced by handleInput(), and updateSnake().
f
struct Snake::Fruit Snake::f private
Referenced by generateFruit(), render(), and updateSnake().
height
const int Snake::height = Size * Size private
Definition at line 32 of file Snake.hpp.
num
int Snake::num = 4 private
Definition at line 33 of file Snake.hpp.
Referenced by checkCollision(), handleInput(), render(), update(), and updateSnake().
s
struct Snake::SnakeSegment Snake::s[100] private
Referenced by checkCollision(), handleInput(), render(), start(), and updateSnake().
Size
const int Snake::Size = 20 private
Definition at line 30 of file Snake.hpp.
Referenced by checkCollision(), generateFruit(), and render().
width
const int Snake::width = Size * Size private
Definition at line 31 of file Snake.hpp.
The documentation for this class was generated from the following files:
games/Snake/Snake.hpp
games/Snake/Snake.cpp