Arcade: IGraphical Class Reference
IGraphical Class Reference abstract
#include <IGraphical.hpp>
Public Member Functions
virtual ~IGraphical ()=default
virtual void createWindow (unsigned int width, unsigned int height, const std::string &title)=0
Create a window object.
virtual void destroyWindow ()=0
Destroy the window object.
virtual void clear () const =0
Clear the window.
virtual void refresh () const =0
Refresh the window.
virtual void display () const =0
Display the window.
virtual void drawRectangle (Vector2f position, Vector2f size, Color color) const =0
Draw a rectangle.
virtual void drawCircle (Vector2f position, float radius, Color color) const =0
Draw a circle.
virtual void drawText (Vector2f position, const std::string &text, unsigned int size, Color color) const =0
Draw a text.
virtual void drawSprite (Vector2f position, const std::string &path) const =0
Draw a sprite.
virtual bool isOpen () const =0
Check if the window is open.
virtual Input getInput ()=0
Get the Input object.
Detailed Description
Definition at line 14 of file IGraphical.hpp.
Constructor & Destructor Documentation
~IGraphical()
virtual IGraphical::~IGraphical () virtual default
Member Function Documentation
clear()
virtual void IGraphical::clear () const pure virtual
Clear the window.
Implemented in SFML, SDL, nCurses, and Allegro.
Referenced by Arcade::Core::displayMenu().
createWindow()
virtual void IGraphical::createWindow (unsigned int width, unsigned int height, const std::string & title) pure virtual
Create a window object.
Parameters
width
height
title
Implemented in SFML, SDL, nCurses, and Allegro.
Referenced by Arcade::Core::displayMenu(), Arcade::Core::launchGame(), and Arcade::Core::switchLibs().
destroyWindow()
virtual void IGraphical::destroyWindow () pure virtual
Destroy the window object.
Implemented in SFML, SDL, nCurses, and Allegro.
Referenced by Arcade::Core::getInputs(), Arcade::Core::launchGame(), and Arcade::Core::switchLibs().
display()
virtual void IGraphical::display () const pure virtual
Display the window.
Implemented in SFML, SDL, nCurses, and Allegro.
Referenced by Arcade::Core::displayMenu().
drawCircle()
virtual void IGraphical::drawCircle (Vector2f position, float radius, Color color) const pure virtual
Draw a circle.
Parameters
position
radius
color
Implemented in SFML, SDL, nCurses, and Allegro.
drawRectangle()
virtual void IGraphical::drawRectangle (Vector2f position, Vector2f size, Color color) const pure virtual
Draw a rectangle.
Parameters
position
size
color
Implemented in SFML, SDL, nCurses, and Allegro.
Referenced by Arcade::Core::displayMenu(), Nibbler::render(), and Snake::render().
drawSprite()
virtual void IGraphical::drawSprite (Vector2f position, const std::string & path) const pure virtual
Draw a sprite.
Parameters
position
path
Implemented in SFML, SDL, nCurses, and Allegro.
Referenced by Arcade::Core::displayMenu().
drawText()
virtual void IGraphical::drawText (Vector2f position, const std::string & text, unsigned int size, Color color) const pure virtual
Draw a text.
Parameters
position
text
size
color
Implemented in SFML, SDL, nCurses, and Allegro.
Referenced by Arcade::Core::drawTextMenu(), Nibbler::render(), and Snake::render().
getInput()
virtual Input IGraphical::getInput () pure virtual
Get the Input object.
Returns
Input
Implemented in SFML, SDL, nCurses, and Allegro.
Referenced by Arcade::Core::getInputs().
isOpen()
virtual bool IGraphical::isOpen () const pure virtual
Check if the window is open.
Returns
true
false
Implemented in SFML, SDL, nCurses, and Allegro.
Referenced by Arcade::Core::displayMenu().
refresh()
virtual void IGraphical::refresh () const pure virtual
Refresh the window.
Implemented in SFML, SDL, nCurses, and Allegro.
The documentation for this class was generated from the following file:
graphicals/IGraphical.hpp