Arcade: Arcade::DLLoader Class Reference
Arcade::DLLoader Class Reference
#include <Core.hpp>
Data Structures
class DLErrorException
Public Member Functions
DLLoader ()=default
~DLLoader ()=default
void * loadLib (const std::string &path)
Load dynamic libraries and display the menu.
void closeLib (void *handle)
Close the library.
template<typename Type >
Type * getSymbol (void *handle, const std::string &sym)
Get the Symbol object (function)
Private Attributes
std::map< std::string, void * > _loaded_libs
Detailed Description
Definition at line 27 of file Core.hpp.
Constructor & Destructor Documentation
DLLoader()
Arcade::DLLoader::DLLoader () default
~DLLoader()
Arcade::DLLoader::~DLLoader () default
Member Function Documentation
closeLib()
void DLLoader::closeLib (void * handle)
Close the library.
Parameters
handle Handle to the library
Definition at line 98 of file Core.cpp.
{
     try {
         if (handle == nullptr)
             throw DLErrorException();
         if (dlclose(handle) != 0)
             throw DLErrorException();
     } catch (DLErrorException &e) {
         std::cerr << e.what() << std::endl;
         exit(84);
     }
 }
References Arcade::DLLoader::DLErrorException::what().
Referenced by Arcade::Core::~Core().
getSymbol()
template<typename Type > Type * DLLoader::getSymbol (void * handle, const std::string & sym)
Get the Symbol object (function)
Parameters
handle Handle to the library
sym Symbol to get (function)
Returns
Type*
Definition at line 118 of file Core.cpp.
{
     Type * (*entry)();
     entry = reinterpret_cast<Type  *(*)()>(dlsym(handle, sym.c_str()));
     Type *symPtr = entry();
     try {
         if (symPtr == nullptr)
             throw DLErrorException();
     } catch (DLErrorException &e) {
         std::cerr << e.what() << std::endl;
         exit(84);
     }
     return symPtr;
 }
References Arcade::DLLoader::DLErrorException::what().
Referenced by Arcade::Core::setGameLib(), and Arcade::Core::setGraphicalLib().
loadLib()
void * DLLoader::loadLib (const std::string & path)
Load dynamic libraries and display the menu.
Parameters
path Path to the library
Definition at line 76 of file Core.cpp.
{
     auto it = _loaded_libs.find(path);
     if (it != _loaded_libs.end()) {
         return it->second;
     }
     void* handle = dlopen(path.c_str(), RTLD_LAZY);
     try {
         if (handle == nullptr)
             throw DLErrorException();
     } catch (DLErrorException &e) {
         std::cerr << e.what() << std::endl;
         exit(84);
     }
     _loaded_libs[path] = handle;
     return handle;
 }
References _loaded_libs, and Arcade::DLLoader::DLErrorException::what().
Referenced by Arcade::Core::setGameLib(), and Arcade::Core::setGraphicalLib().
Field Documentation
_loaded_libs
std::map<std::string, void*> Arcade::DLLoader::_loaded_libs private
Definition at line 44 of file Core.hpp.
Referenced by loadLib().
The documentation for this class was generated from the following files:
core/Core.hpp
core/Core.cpp