Arcade: Nibbler Class Reference
Nibbler Class Reference
#include <Nibbler.hpp>
Data Structures
struct Fruit
struct NibblerSegment
Public Member Functions
~Nibbler () override
void init (IGraphical *graphics, std::string playerName) override
Initialize the game.
void update () override
Update the game each frame.
void handleInput (Input input) override
Handle the input of the player.
void render () override
Render the game.
std::string getName () const override
Get the Name of the game.
unsigned int getCurrentScore () const override
Get the Current Score of the game.
unsigned int getHighScore () const override
Get the High Score of the game.
void setState (GameState state) override
Set the State of the game.
GameState getState () const override
Get the State of the game.
Public Member Functions inherited from IGame
IGame ()=default
virtual ~IGame ()=default
Private Member Functions
void start ()
void generateFruit ()
void updateNibbler ()
bool checkCollision ()
void loadHighScores ()
void saveHighScores ()
void updateHighScore ()
void displayHighScores ()
void print_map_and_fruit ()
void changeMap ()
void respawnSnake ()
void delay (int milliseconds)
std::vector< std::vector< char > > readMapNibbler (std::string fileName)
Private Attributes
const int Size = 20
const int width = Size * Size
const int height = Size * Size
int num = 4
int dir = 1
bool _firstStart = true
std::vector< std::vector< char > > map
int _nbFruit = 5
unsigned int _level = 0
struct Nibbler::NibblerSegment s [100]
struct Nibbler::Fruit f [5]
unsigned int _currentScore = 0
unsigned int _highScore = 0
std::unordered_map< std::string, unsigned int > _highScores
std::string _playerName
GameState _state = GameState::PAUSED
IGraphical * _graphics
Additional Inherited Members
Protected Attributes inherited from IGame
GameState _state = GameState::PAUSED
unsigned int _currentScore
unsigned int _highScore
std::unordered_map< std::string, unsigned int > _highScores
std::string _playerName
IGraphical * _graphical
Detailed Description
Definition at line 19 of file Nibbler.hpp.
Constructor & Destructor Documentation
~Nibbler()
Nibbler::~Nibbler () inline override
Definition at line 21 of file Nibbler.hpp.
 {}
Member Function Documentation
changeMap()
void Nibbler::changeMap () private
Definition at line 149 of file Nibbler.cpp.
{
     if (_level == 0) {
         map.clear();
         map = readMapNibbler(MAP_2);
         generateFruit();
         _level = 1;
         respawnSnake();
     } else if (_level == 1) {
         map.clear();
         map = readMapNibbler(MAP_3);
         generateFruit();
         _level = 2;
         respawnSnake();
     } else if (_level == 2) {
         _state = GameState::WIN;
     }
 }
References _level, _state, generateFruit(), map, MAP_2, MAP_3, readMapNibbler(), respawnSnake(), and WIN.
Referenced by updateNibbler().
checkCollision()
bool Nibbler::checkCollision () private
Definition at line 196 of file Nibbler.cpp.
{
     for (int i = 1; i < num; i++) {
         if (s[0].x == s[i].x && s[0].y == s[i].y) {
             return true;
         }
     }
     // Coming from the left
     if (map[s[0].y][s[0].x + 1] == WALL && dir == 1) {
         if (map[s[0].y - 1][s[0].x] == WALL)
             dir = 2;
         else
             dir = 0;
         updateNibbler();
     }
     // Coming from the right
     if (map[s[0].y][s[0].x - 1] == WALL && dir == 3) {
         if (map[s[0].y + 1][s[0].x] == WALL)
             dir = 0;
         else
             dir = 2;
         updateNibbler();
     }
     // Coming from the top
     if (map[s[0].y + 1][s[0].x] == WALL && dir == 2) {
         if (map[s[0].y][s[0].x - 1] == WALL)
             dir = 1;
         else
             dir = 3;
         updateNibbler();
     }
     // Coming from the bottom
     if (map[s[0].y - 1][s[0].x] == WALL && dir == 0) {
         if (map[s[0].y][s[0].x + 1] == WALL)
             dir = 3;
         else
             dir = 1;
         updateNibbler();
     }
     return false;
 }
References dir, map, num, s, updateNibbler(), and WALL.
Referenced by update().
delay()
void Nibbler::delay (int milliseconds) private
Definition at line 293 of file Nibbler.cpp.
{
     auto start_time = std::chrono::high_resolution_clock::now();
     while (std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now() - start_time).count() < milliseconds) {}
 }
Referenced by updateNibbler().
displayHighScores()
void Nibbler::displayHighScores () private
generateFruit()
void Nibbler::generateFruit () private
Definition at line 132 of file Nibbler.cpp.
{
     std::srand(std::time(nullptr));
     int numFruit = _nbFruit;
     int rows = map.size();
     int cols = map[0].size();
     while (numFruit > 0) {
         int row = std::rand() % rows;
         int col = std::rand() % cols;
         if (map[row][col] == EMPTY) {
             f[numFruit].x = col;
             f[numFruit].y = row;
             numFruit--;
         }
     }
 }
References _nbFruit, EMPTY, f, map, Nibbler::Fruit::x, and Nibbler::Fruit::y.
Referenced by changeMap(), and start().
getCurrentScore()
unsigned int Nibbler::getCurrentScore () const inline override virtual
Get the Current Score of the game.
Returns
unsigned int The current score of the game
Implements IGame.
Definition at line 29 of file Nibbler.hpp.
 { return _currentScore; }
References _currentScore.
getHighScore()
unsigned int Nibbler::getHighScore () const inline override virtual
Get the High Score of the game.
Returns
unsigned int The high score of the game
Implements IGame.
Definition at line 30 of file Nibbler.hpp.
 { return _highScore; }
References _highScore.
getName()
std::string Nibbler::getName () const inline override virtual
Get the Name of the game.
Returns
std::string The name of the game
Implements IGame.
Definition at line 28 of file Nibbler.hpp.
 { return "Nibbler"; }
getState()
GameState Nibbler::getState () const inline override virtual
Get the State of the game.
Returns
GameState The state of the game (RUNNING, PAUSED, GAME_OVER, WIN)
Implements IGame.
Definition at line 32 of file Nibbler.hpp.
 { return _state; }
References _state.
handleInput()
void Nibbler::handleInput (Input input) override virtual
Handle the input of the player.
Parameters
input The input of the player
Implements IGame.
Definition at line 56 of file Nibbler.cpp.
{
     if (input == Input::Z && dir != 2 && map[s[0].y - 1][s[0].x] != WALL)
         dir = 0;
     if (input == Input::D && dir != 3 && map[s[0].y][s[0].x + 1] != WALL)
         dir = 1;
     if (input == Input::S && dir != 0 && map[s[0].y + 1][s[0].x] != WALL)
         dir = 2;
     if (input == Input::Q && dir != 1 && map[s[0].y][s[0].x - 1] != WALL)
         dir = 3;
     if (input == Input::SPACE) {
         _state = GameState::RUNNING;
         _currentScore = 0;
         num = 4;
         respawnSnake();
         start();
     }
     if (input == Input::BACKSPACE)
         _state = GameState::GAME_OVER;
 }
References _currentScore, _state, BACKSPACE, D, dir, GAME_OVER, map, num, Q, respawnSnake(), RUNNING, S, s, SPACE, start(), WALL, and Z.
init()
void Nibbler::init (IGraphical * graphics, std::string playerName) override virtual
Initialize the game.
Parameters
graphics The graphical library to use
playerName The player name of the current player
Implements IGame.
Definition at line 10 of file Nibbler.cpp.
{
     _graphical = graphics;
     _playerName = playerName;
     loadHighScores();
     if (_firstStart)
         start();
 }
References _firstStart, IGame::_graphical, _playerName, loadHighScores(), and start().
loadHighScores()
void Nibbler::loadHighScores () private
Definition at line 257 of file Nibbler.cpp.
{
     std::ifstream file(NIBBLER_HIGHSCORES_FILE);
     if (file.is_open()) {
         // Read the high scores from the file
         std::string line;
         while (std::getline(file, line)) {
             std::stringstream ss(line);
             std::string playerName;
             unsigned int highScore;
             ss >> playerName >> highScore;
             _highScores[playerName] = highScore;
         }
         file.close();
     }
     else {
         // If the file does not exist, create it with empty high scores
         saveHighScores();
     }
     // Load the high score for the current player
     if (_highScores.find(_playerName) != _highScores.end()) {
         _highScore = _highScores[_playerName];
     }
 }
References _highScore, _highScores, _playerName, NIBBLER_HIGHSCORES_FILE, and saveHighScores().
Referenced by init().
print_map_and_fruit()
void Nibbler::print_map_and_fruit () private
readMapNibbler()
std::vector< std::vector< char > > Nibbler::readMapNibbler (std::string fileName) private
Definition at line 76 of file Nibbler.cpp.
{
     std::ifstream file(fileName);
     std::vector<std::vector<char>> map;
     std::string line;
     while (std::getline(file, line)) {
         std::vector<char> row;
         for (char c : line) {
             row.push_back(c);
         }
         map.push_back(row);
     }
     return map;
 }
References map.
Referenced by changeMap(), and start().
render()
void Nibbler::render () override virtual
Render the game.
Implements IGame.
Definition at line 92 of file Nibbler.cpp.
                      {
     int Mx = 0;
     int My = 0;
     int i = 0;
     for (auto& row : map) {
         for (auto& c : row) {
             if (c == WALL) {
                 _graphical->drawRectangle(Vector2f(START_WIN_X + Mx, START_WIN_Y + My), Vector2f(Size, Size), Color::WHITE);
             }
             if (c == EMPTY) {
                 _graphical->drawRectangle(Vector2f(START_WIN_X + Mx, START_WIN_Y + My), Vector2f(Size, Size), Color::BLACK);
             }
             Mx += Size;
         }
         Mx = 0;
         My += Size;
     }
     for (int i = 0; i < num; i++) {
         _graphical->drawRectangle(Vector2f(s[i].x * Size + START_WIN_X, s[i].y * Size + START_WIN_Y), Vector2f(20, 20), Color::RED);
         _graphical->drawRectangle(Vector2f(s[0].x * Size + START_WIN_X, s[0].y * Size + START_WIN_Y), Vector2f(20, 20), Color::BLUE);
     }
     _graphical->drawText(Vector2f(START_WIN_X + 500, START_WIN_Y + 100), "High Scores :", 14, Color::WHITE);
     for (auto& entry : _highScores) {
         _graphical->drawText(Vector2f(START_WIN_X + 500, START_WIN_Y + 150 + (i * 20)), entry.first + " : " + std::to_string(entry.second), 14, Color::WHITE);
         i++;
     }
     _graphical->drawText(Vector2f(START_WIN_X + 150, START_WIN_Y - 100), "Current Score : " + std::to_string(_currentScore), 18, Color::WHITE);
     for (int i = 0; i < _nbFruit; i++)
         _graphical->drawRectangle(Vector2f(f[i].x * Size + START_WIN_X, f[i].y * Size + START_WIN_Y), Vector2f(20, 20), Color::MAGENTA);
     _graphical->drawRectangle(Vector2f(START_WIN_X, START_WIN_Y), Vector2f(20, 20), Color::WHITE);
     if (_state == GameState::WIN) {
         _graphical->drawText(Vector2f(START_WIN_X + 170, START_WIN_Y + 480), "You Win !", 20, Color::WHITE);
         _graphical->drawText(Vector2f(START_WIN_X + 70, START_WIN_Y + 510), "Press Backspace to go back to menu", 16, Color::WHITE);
     }
 }
References _currentScore, IGame::_graphical, _highScores, _nbFruit, _state, BLACK, BLUE, IGraphical::drawRectangle(), IGraphical::drawText(), EMPTY, f, MAGENTA, map, num, RED, s, Size, START_WIN_X, START_WIN_Y, WALL, WHITE, and WIN.
respawnSnake()
void Nibbler::respawnSnake () private
Definition at line 32 of file Nibbler.cpp.
{
     s[0].x = 10;
     s[0].y = 10;
     num = 4;
     dir = 0;
     for (int i = 1; i < num; i++) {
         s[i].x = 10;
         s[i].y = 11;
     }
 }
References dir, num, s, Nibbler::NibblerSegment::x, and Nibbler::NibblerSegment::y.
Referenced by changeMap(), and handleInput().
saveHighScores()
void Nibbler::saveHighScores () private
Definition at line 244 of file Nibbler.cpp.
{
     std::ofstream file(NIBBLER_HIGHSCORES_FILE);
     if (file.is_open()) {
         // Write the high scores to the file
         for (auto& entry : _highScores) {
             file << entry.first << " " << entry.second << std::endl;
         }
         file.close();
     }
 }
References _highScores, and NIBBLER_HIGHSCORES_FILE.
Referenced by loadHighScores(), and updateHighScore().
setState()
void Nibbler::setState (GameState state) inline override virtual
Set the State of the game.
Parameters
state The state of the game (RUNNING, PAUSED, GAME_OVER, WIN)
Implements IGame.
Definition at line 31 of file Nibbler.hpp.
 { _state = state; }
References _state.
start()
void Nibbler::start () private
Definition at line 20 of file Nibbler.cpp.
                     {
     srand(time(nullptr));
     map = readMapNibbler(MAP_1);
     s[0].x = 10;
     s[0].y = 10;
     generateFruit();
     _level = 0;
     _firstStart = false;
 }
References _firstStart, _level, generateFruit(), map, MAP_1, readMapNibbler(), s, Nibbler::NibblerSegment::x, and Nibbler::NibblerSegment::y.
Referenced by handleInput(), and init().
update()
void Nibbler::update () override virtual
Update the game each frame.
Implements IGame.
Definition at line 43 of file Nibbler.cpp.
                      {
     if (_state == GameState::RUNNING) {
         _currentScore = _level;
         if (checkCollision()) {
             _state = GameState::GAME_OVER;
             updateHighScore();
             return;
         }
         updateNibbler();
     }
 }
References _currentScore, _level, _state, checkCollision(), GAME_OVER, RUNNING, updateHighScore(), and updateNibbler().
updateHighScore()
void Nibbler::updateHighScore () private
Definition at line 284 of file Nibbler.cpp.
{
     // Update the high score for the current player
     if (_currentScore > _highScore) {
         _highScore = _currentScore;
         _highScores[_playerName] = _highScore;
         saveHighScores();
     }
 }
References _currentScore, _highScore, _highScores, _playerName, and saveHighScores().
Referenced by update().
updateNibbler()
void Nibbler::updateNibbler () private
Definition at line 167 of file Nibbler.cpp.
{
     for (int i = num - 1; i > 0; --i) {
         s[i].x = s[i - 1].x;
         s[i].y = s[i - 1].y;
     }
     if (dir == 0) s[0].y -= 1;
     if (dir == 1) s[0].x += 1;
     if (dir == 2) s[0].y += 1;
     if (dir == 3) s[0].x -= 1;
     for (int i = 0; i < _nbFruit; i++) {
         if ((s[0].x == f[i].x) && (s[0].y == f[i].y)) {
             f[i].x = -100;
             f[i].y = -100;
             num++;
         }
     }
     delay(150);
     for (int i = 1; i < _nbFruit; i++) {
         if (f[i].x != -100 && f[i].y != -100) {
             return;
         }
     }
     changeMap();
 }
References _nbFruit, changeMap(), delay(), dir, f, num, s, Nibbler::NibblerSegment::x, Nibbler::Fruit::x, Nibbler::NibblerSegment::y, and Nibbler::Fruit::y.
Referenced by checkCollision(), and update().
Field Documentation
_currentScore
unsigned int Nibbler::_currentScore = 0 private
Definition at line 53 of file Nibbler.hpp.
Referenced by getCurrentScore(), handleInput(), render(), update(), and updateHighScore().
_firstStart
bool Nibbler::_firstStart = true private
Definition at line 40 of file Nibbler.hpp.
Referenced by init(), and start().
_graphics
IGraphical* Nibbler::_graphics private
Definition at line 59 of file Nibbler.hpp.
_highScore
unsigned int Nibbler::_highScore = 0 private
Definition at line 54 of file Nibbler.hpp.
Referenced by getHighScore(), loadHighScores(), and updateHighScore().
_highScores
std::unordered_map<std::string, unsigned int> Nibbler::_highScores private
Definition at line 55 of file Nibbler.hpp.
Referenced by loadHighScores(), render(), saveHighScores(), and updateHighScore().
_level
unsigned int Nibbler::_level = 0 private
Definition at line 43 of file Nibbler.hpp.
Referenced by changeMap(), start(), and update().
_nbFruit
int Nibbler::_nbFruit = 5 private
Definition at line 42 of file Nibbler.hpp.
Referenced by generateFruit(), render(), and updateNibbler().
_playerName
std::string Nibbler::_playerName private
Definition at line 56 of file Nibbler.hpp.
Referenced by init(), loadHighScores(), and updateHighScore().
_state
GameState Nibbler::_state = GameState::PAUSED private
Definition at line 57 of file Nibbler.hpp.
Referenced by changeMap(), getState(), handleInput(), render(), setState(), and update().
dir
int Nibbler::dir = 1 private
Definition at line 39 of file Nibbler.hpp.
Referenced by checkCollision(), handleInput(), respawnSnake(), and updateNibbler().
f
struct Nibbler::Fruit Nibbler::f[5] private
Referenced by generateFruit(), render(), and updateNibbler().
height
const int Nibbler::height = Size * Size private
Definition at line 37 of file Nibbler.hpp.
map
std::vector<std::vector<char> > Nibbler::map private
Definition at line 41 of file Nibbler.hpp.
Referenced by changeMap(), checkCollision(), generateFruit(), handleInput(), readMapNibbler(), render(), and start().
num
int Nibbler::num = 4 private
Definition at line 38 of file Nibbler.hpp.
Referenced by checkCollision(), handleInput(), render(), respawnSnake(), and updateNibbler().
s
struct Nibbler::NibblerSegment Nibbler::s[100] private
Referenced by checkCollision(), handleInput(), render(), respawnSnake(), start(), and updateNibbler().
Size
const int Nibbler::Size = 20 private
Definition at line 35 of file Nibbler.hpp.
Referenced by render().
width
const int Nibbler::width = Size * Size private
Definition at line 36 of file Nibbler.hpp.
The documentation for this class was generated from the following files:
games/Nibbler/Nibbler.hpp
games/Nibbler/Nibbler.cpp