Arcade: Allegro Class Reference
Allegro Class Reference
#include <Allegro.hpp>
Public Member Functions
Allegro ()
~Allegro () override
void createWindow (unsigned int width, unsigned int height, const std::string &title) override
Create a window object.
void destroyWindow () override
Destroy the window object.
void clear () const override
Clear the window.
void refresh () const override
Refresh the window.
void display () const override
Display the window.
void drawRectangle (Vector2f position, Vector2f size, Color color) const override
Draw a rectangle.
void drawCircle (Vector2f position, float radius, Color color) const override
Draw a circle.
void drawText (Vector2f position, const std::string &text, unsigned int size, Color color) const override
Draw a text.
void drawSprite (Vector2f position, const std::string &path) const override
Draw a sprite.
bool isOpen () const override
Check if the window is open.
Input getInput () override
Get the Input object.
ALLEGRO_COLOR getColor (Color color) const
Public Member Functions inherited from IGraphical
virtual ~IGraphical ()=default
Private Attributes
ALLEGRO_DISPLAY * _window
ALLEGRO_EVENT_QUEUE * _event
ALLEGRO_FONT * _font
int _width
int _height
std::string _title
Input _input
Detailed Description
Definition at line 20 of file Allegro.hpp.
Constructor & Destructor Documentation
Allegro()
Allegro::Allegro ()
Definition at line 10 of file Allegro.cpp.
                  {
     try {
         if (!al_init())
             throw AllegroError("Allegro initialization failed");
         if (!al_init_ttf_addon())
             throw AllegroError("Allegro ttf addon initialization failed");
         if (!al_init_image_addon())
             throw AllegroError("Allegro image addon initialization failed");
         if (!al_init_primitives_addon())
             throw AllegroError("Allegro primitives addon initialization failed");
         if (!al_install_keyboard())
             throw AllegroError("Allegro keyboard installation failed");
         _font = al_load_ttf_font("./graphicals/SUBWT___.ttf", 20, 0);
         if (!_font)
             throw AllegroError("Allegro font loading failed");
         _event = al_create_event_queue();
         if (!_event)
             throw AllegroError("Allegro event queue creation failed");
         al_register_event_source(_event, al_get_keyboard_event_source());
     } catch (const AllegroError &e) {
         std::cerr << e.what() << std::endl;
         exit(84);
     }
 }
References _event, and _font.
~Allegro()
Allegro::~Allegro () override
Definition at line 35 of file Allegro.cpp.
                   {
     al_destroy_font(_font);
     al_destroy_event_queue(_event);
 }
References _event, and _font.
Member Function Documentation
clear()
void Allegro::clear () const override virtual
Clear the window.
Implements IGraphical.
Definition at line 59 of file Allegro.cpp.
{
     al_clear_to_color(al_map_rgb(255, 255, 255));
 }
createWindow()
void Allegro::createWindow (unsigned int width, unsigned int height, const std::string & title) override virtual
Create a window object.
Parameters
width
height
title
Implements IGraphical.
Definition at line 40 of file Allegro.cpp.
{
     _width = width;
     _height = height;
     _title = title;
     _window = al_create_display(width, height);
     try {
         if (_window == nullptr)
             throw AllegroError("Allegro window creation failed");
     } catch (const AllegroError &e) {
         std::cerr << e.what() << std::endl;
         exit(84);
     }
     al_clear_to_color(al_map_rgb(255, 255, 255));
 }
References _height, _title, _width, and _window.
destroyWindow()
void Allegro::destroyWindow () override virtual
Destroy the window object.
Implements IGraphical.
Definition at line 55 of file Allegro.cpp.
{
     al_destroy_display(_window);
 }
References _window.
display()
void Allegro::display () const override virtual
Display the window.
Implements IGraphical.
Definition at line 67 of file Allegro.cpp.
{
     al_flip_display();
 }
drawCircle()
void Allegro::drawCircle (Vector2f position, float radius, Color color) const override virtual
Draw a circle.
Parameters
position
radius
color
Implements IGraphical.
Definition at line 76 of file Allegro.cpp.
{
     al_draw_filled_circle(position.x, position.y, radius, getColor(color));
 }
References getColor(), Vector2f::x, and Vector2f::y.
drawRectangle()
void Allegro::drawRectangle (Vector2f position, Vector2f size, Color color) const override virtual
Draw a rectangle.
Parameters
position
size
color
Implements IGraphical.
Definition at line 71 of file Allegro.cpp.
{
     al_draw_filled_rectangle(position.x, position.y, position.x + size.x, position.y + size.y, getColor(color));
     al_draw_rectangle(position.x, position.y, position.x + size.x, position.y + size.y, al_map_rgb(0, 0, 0), 1);
 }
References getColor(), Vector2f::x, and Vector2f::y.
drawSprite()
void Allegro::drawSprite (Vector2f position, const std::string & path) const override virtual
Draw a sprite.
Parameters
position
path
Implements IGraphical.
Definition at line 85 of file Allegro.cpp.
{
     ALLEGRO_BITMAP *sprite = al_load_bitmap(path.c_str());
     al_draw_bitmap(sprite, position.x, position.y, 0);
     al_destroy_bitmap(sprite);
 }
References Vector2f::x, and Vector2f::y.
drawText()
void Allegro::drawText (Vector2f position, const std::string & text, unsigned int size, Color color) const override virtual
Draw a text.
Parameters
position
text
size
color
Implements IGraphical.
Definition at line 80 of file Allegro.cpp.
{
     (void)(size);
     al_draw_text(_font, getColor(color), position.x, position.y, 0, text.c_str());
 }
References _font, getColor(), Vector2f::x, and Vector2f::y.
getColor()
ALLEGRO_COLOR Allegro::getColor (Color color) const
Definition at line 138 of file Allegro.cpp.
{
     switch (color) {
         case RED:
             return al_map_rgb(255, 0, 0);
         case GREEN:
             return al_map_rgb(0, 255, 0);
         case BLUE:
             return al_map_rgb(0, 0, 255);
         case YELLOW:
             return al_map_rgb(255, 255, 0);
         case MAGENTA:
             return al_map_rgb(255, 0, 255);
         case CYAN:
             return al_map_rgb(0, 255, 255);
         case WHITE:
             return al_map_rgb(255, 255, 255);
         case BLACK:
             return al_map_rgb(0, 0, 0);
         default:
             return al_map_rgb(255, 255, 255);
     }
 }
References BLACK, BLUE, CYAN, GREEN, MAGENTA, RED, WHITE, and YELLOW.
Referenced by drawCircle(), drawRectangle(), and drawText().
getInput()
Input Allegro::getInput () override virtual
Get the Input object.
Returns
Input
Implements IGraphical.
Definition at line 96 of file Allegro.cpp.
{
     ALLEGRO_EVENT event;
     while (al_get_next_event(_event, &event)) {
         if (event.type == ALLEGRO_EVENT_KEY_DOWN) {
             switch (event.keyboard.keycode) {
                 case ALLEGRO_KEY_UP:
                     return UP;
                 case ALLEGRO_KEY_DOWN:
                     return DOWN;
                 case ALLEGRO_KEY_LEFT:
                     return LEFT;
                 case ALLEGRO_KEY_RIGHT:
                     return RIGHT;
                 case ALLEGRO_KEY_ENTER:
                     return ENTER;
                 case ALLEGRO_KEY_ESCAPE:
                     return ESCAPE;
                 case ALLEGRO_KEY_SPACE:
                     return SPACE;
                 case ALLEGRO_KEY_BACKSPACE:
                     return BACKSPACE;
                 case ALLEGRO_KEY_A:
                     return A;
                 case ALLEGRO_KEY_D:
                     return D;
                 case ALLEGRO_KEY_E:
                     return E;
                     return Q;
                 case ALLEGRO_KEY_S:
                     return S;
                 case ALLEGRO_KEY_Z:
                     return Z;
                 case ALLEGRO_KEY_Q:
                     return Q;
                 default:
                     return NONE;
             }
         }
     }
     return NONE;
 }
References _event, A, BACKSPACE, D, DOWN, E, ENTER, ESCAPE, LEFT, NONE, Q, RIGHT, S, SPACE, UP, and Z.
isOpen()
bool Allegro::isOpen () const override virtual
Check if the window is open.
Returns
true
false
Implements IGraphical.
Definition at line 92 of file Allegro.cpp.
{
     return _window != nullptr;
 }
References _window.
refresh()
void Allegro::refresh () const override virtual
Refresh the window.
Implements IGraphical.
Definition at line 63 of file Allegro.cpp.
{
     al_flip_display();
 }
Field Documentation
_event
ALLEGRO_EVENT_QUEUE* Allegro::_event private
Definition at line 43 of file Allegro.hpp.
Referenced by Allegro(), getInput(), and ~Allegro().
_font
ALLEGRO_FONT* Allegro::_font private
Definition at line 44 of file Allegro.hpp.
Referenced by Allegro(), drawText(), and ~Allegro().
_height
int Allegro::_height private
Definition at line 46 of file Allegro.hpp.
Referenced by createWindow().
_input
Input Allegro::_input private
Definition at line 49 of file Allegro.hpp.
_title
std::string Allegro::_title private
Definition at line 47 of file Allegro.hpp.
Referenced by createWindow().
_width
int Allegro::_width private
Definition at line 45 of file Allegro.hpp.
Referenced by createWindow().
_window
ALLEGRO_DISPLAY* Allegro::_window private
Definition at line 42 of file Allegro.hpp.
Referenced by createWindow(), destroyWindow(), and isOpen().
The documentation for this class was generated from the following files:
graphicals/Allegro/Allegro.hpp
graphicals/Allegro/Allegro.cpp