Arcade: Arcade::Core Class Reference
Arcade::Core Class Reference
#include <Core.hpp>
Public Member Functions
Core (const std::string &libPath)
Init Core of the Arcade.
~Core ()
Destroy the Core object.
void setGameLib (const std::string &gamePath)
Set the Game Lib object.
void setGraphicalLib (const std::string &graphicalPath)
Set the Graphical Lib object.
void findLibs (std::vector< std::string > &games, std::vector< std::string > &graphics)
Find all the libraries in the lib folder.
void switchLibs (std::vector< std::string > graphics, bool Direction)
Switch between the graphical libraries.
void displayMenu (const std::string libPath)
Display the Menu.
void drawTextMenu (std::vector< std::string > games, std::vector< std::string > graphics, bool isGame)
Draw the Text Menu.
Input getInputs (std::vector< std::string > games, std::vector< std::string > graphics, bool &isGame)
Get Inout of player for the Menu.
void gameLoop (Input input)
Call IGame functions to handle the game.
void launchGame (bool isGame, std::vector< std::string > games, std::vector< std::string > graphics)
Launch the game selected.
Private Attributes
void * _handle_game = nullptr
IGame * _game = nullptr
std::string _playerName = "Player"
void * _handle_graphical = nullptr
IGraphical * _graphical = nullptr
DLLoader _dl
bool _isInGame = false
bool _gameStarted = false
int _selectedGameIndex = 0
int _selectedGraphicsIndex = 0
Detailed Description
Definition at line 46 of file Core.hpp.
Constructor & Destructor Documentation
Core()
Core::Core (const std::string & libPath)
Init Core of the Arcade.
Parameters
libPath Default library path to use
Definition at line 17 of file Core.cpp.
{
     std::cout << "Enter your name: ";
     std::cin >> _playerName;
     if (std::cin.fail()) {
         std::cerr << "Error: Invalid name" << std::endl;
         exit(84);
     }
     _handle_game = nullptr;
     _handle_graphical = nullptr;
     _dl = DLLoader();
     LibList libList;
     for (auto &it : libList.graphics) {
         if (it == libPath) {
             displayMenu(libPath);
         }
     }
     std::cerr << "Error: Invalid library - Please use a graphical library" << std::endl;
     exit(84);
 }
References _dl, _handle_game, _handle_graphical, _playerName, displayMenu(), and LibList::graphics.
~Core()
Core::~Core ()
Destroy the Core object.
Definition at line 44 of file Core.cpp.
             {
     if (_handle_game)
         _dl.closeLib(_handle_game);
     if (_handle_graphical)
         _dl.closeLib(_handle_graphical);
 }
References _dl, _handle_game, _handle_graphical, and Arcade::DLLoader::closeLib().
Member Function Documentation
displayMenu()
void Core::displayMenu (const std::string libPath)
Display the Menu.
Parameters
libPath Path of the graphical library
Definition at line 291 of file Core.cpp.
{
     std::vector<std::string> games;
     std::vector<std::string> graphics;
     bool isGame = true;
     findLibs(games, graphics);
     setGraphicalLib(libPath);
     _graphical->createWindow(WIDTH, HEIGHT, TITLE);
     while (_graphical->isOpen()) {
         _graphical->clear();
         _graphical->drawRectangle(Vector2f(-50, -50), Vector2f(WIDTH + 100, HEIGHT + 100), Color::TRANSPARENT);
         _graphical->drawSprite(Vector2f(-50, 0), BACKGROUND_PATH);
         Input input = getInputs(games, graphics, isGame);
         drawTextMenu(games, graphics, isGame);
         gameLoop(input);
         _graphical->display();
     }
 }
References _graphical, BACKGROUND_PATH, IGraphical::clear(), IGraphical::createWindow(), IGraphical::display(), IGraphical::drawRectangle(), IGraphical::drawSprite(), drawTextMenu(), findLibs(), gameLoop(), getInputs(), HEIGHT, IGraphical::isOpen(), setGraphicalLib(), TITLE, TRANSPARENT, and WIDTH.
Referenced by Core().
drawTextMenu()
void Core::drawTextMenu (std::vector< std::string > games, std::vector< std::string > graphics, bool isGame)
Draw the Text Menu.
Parameters
games Vector of games
graphics Vector of graphical libraries
isGame Is the player in the game selection
Definition at line 238 of file Core.cpp.
{
     /* Games Categorie */
     if (!_isInGame && !_gameStarted) {
         _graphical->drawText(Vector2f(X_MIDDLE, Y_MIDDLE - 20), "Games:", 16, Color::WHITE);
         for (std::size_t i = 0; i < games.size(); i++) {
             if ((int) i == _selectedGameIndex)
                 _graphical->drawText(Vector2f(X_MIDDLE, Y_MIDDLE + ((i * 20) + 20)), games[i], 16, Color::CYAN);
             else
                 _graphical->drawText(Vector2f(X_MIDDLE, Y_MIDDLE + ((i * 20) + 20)), games[i], 16, Color::WHITE);
         }
     }
     /* User */
     _graphical->drawText(Vector2f(30, 30), "Logged as: " + _playerName, 16, Color::WHITE);
     /* Graphical Categorie */
     _graphical->drawText(Vector2f(30, Y_MIDDLE - 20), "Graphics:", 16, Color::WHITE);
     for (std::size_t i = 0; i < graphics.size(); i++) {
         if ((int) i == _selectedGraphicsIndex)
             _graphical->drawText(Vector2f(30, Y_MIDDLE + ((i * 20) + 20)), graphics[i], 16, Color::CYAN);
         else
             _graphical->drawText(Vector2f(30, Y_MIDDLE + ((i * 20) + 20)), graphics[i], 16, Color::WHITE);
     }
     /* LibSelected */
     if (isGame && !_isInGame)
         _graphical->drawText(Vector2f(X_MIDDLE - 20, Y_MIDDLE + ((_selectedGameIndex * 20) + 20)), ">", 16, Color::WHITE);
     else
         _graphical->drawText(Vector2f(30 - 20, Y_MIDDLE + ((_selectedGraphicsIndex * 20) + 20)), ">", 16, Color::WHITE);
 }
References _gameStarted, _graphical, _isInGame, _playerName, _selectedGameIndex, _selectedGraphicsIndex, CYAN, IGraphical::drawText(), WHITE, X_MIDDLE, and Y_MIDDLE.
Referenced by displayMenu().
findLibs()
void Core::findLibs (std::vector< std::string > & games, std::vector< std::string > & graphics)
Find all the libraries in the lib folder.
Parameters
games Vector of games
graphics Vector of graphical libraries
Definition at line 138 of file Core.cpp.
{
     std::filesystem::path path = "lib/";
     LibList libList;
     for (const auto &entry : std::filesystem::directory_iterator(path)) {
         std::string filePath = entry.path().string();
         if (std::find(libList.games.begin(), libList.games.end(), filePath) != libList.games.end())
             games.push_back(filePath);
         else if (std::find(libList.graphics.begin(), libList.graphics.end(), filePath) != libList.graphics.end())
             graphics.push_back(filePath);
     }
 }
References LibList::games, and LibList::graphics.
Referenced by displayMenu().
gameLoop()
void Core::gameLoop (Input input)
Call IGame functions to handle the game.
Parameters
input Input of the player
Definition at line 274 of file Core.cpp.
{
     if (_game != nullptr && _gameStarted) {
         _game->handleInput(input);
         _game->update();
         _game->render();
         if (_game->getState() == GameState::GAME_OVER) {
             _isInGame = false;
             _gameStarted = false;
         }
     }
 }
References _game, _gameStarted, _isInGame, GAME_OVER, IGame::getState(), IGame::handleInput(), IGame::render(), and IGame::update().
Referenced by displayMenu().
getInputs()
Input Core::getInputs (std::vector< std::string > games, std::vector< std::string > graphics, bool & isGame)
Get Inout of player for the Menu.
Parameters
games Vector of games
graphics Vector of graphical libraries
isGame Is the player in the game selection
Definition at line 201 of file Core.cpp.
{
     Input input = _graphical->getInput();
     if (input == Input::ESCAPE) {
         _graphical->destroyWindow();
         exit(0);
     }
     if (input == Input::UP && isGame)
         _selectedGameIndex = (_selectedGameIndex + 1) % games.size();
     else if (input == Input::DOWN && isGame)
         _selectedGameIndex = (_selectedGameIndex + games.size() - 1) % games.size();
     else if (input == Input::UP && !isGame)
         _selectedGraphicsIndex = (_selectedGraphicsIndex + graphics.size() - 1) % graphics.size();
     else if (input == Input::DOWN && !isGame)
         _selectedGraphicsIndex = (_selectedGraphicsIndex + 1) % graphics.size();
     else if (input == Input::LEFT)
         isGame = !isGame;
     else if (input == Input::RIGHT)
         isGame = !isGame;
     else if (input == Input::ENTER)
         launchGame(isGame, games, graphics);
     else if (input == Input::A && _gameStarted)
         switchLibs(graphics, false);
     else if (input == Input::E && _gameStarted)
         switchLibs(graphics, true);
     return input;
 }
References _gameStarted, _graphical, _selectedGameIndex, _selectedGraphicsIndex, A, IGraphical::destroyWindow(), DOWN, E, ENTER, ESCAPE, IGraphical::getInput(), launchGame(), LEFT, RIGHT, switchLibs(), and UP.
Referenced by displayMenu().
launchGame()
void Core::launchGame (bool isGame, std::vector< std::string > games, std::vector< std::string > graphics)
Launch the game selected.
Parameters
isGame Is the player in the game selection
games Vector of games
graphics Vector of graphical libraries
Definition at line 159 of file Core.cpp.
{
     if (isGame && !_isInGame) {
         setGameLib(games[_selectedGameIndex]);
         isGame = false;
         _isInGame = true;
         _game->setState(GameState::RUNNING);
         _game->init(_graphical, _playerName);
         _gameStarted = true;
     } else {
         _graphical->destroyWindow();
         setGraphicalLib(graphics[_selectedGraphicsIndex]);
         _graphical->createWindow(WIDTH, HEIGHT, TITLE);
         if (_gameStarted)
             _game->init(_graphical, _playerName);
     }
 }
References _game, _gameStarted, _graphical, _isInGame, _playerName, _selectedGameIndex, _selectedGraphicsIndex, IGraphical::createWindow(), IGraphical::destroyWindow(), HEIGHT, IGame::init(), RUNNING, setGameLib(), setGraphicalLib(), IGame::setState(), TITLE, and WIDTH.
Referenced by getInputs().
setGameLib()
void Core::setGameLib (const std::string & gamePath)
Set the Game Lib object.
Parameters
gamePath Path to the game library
Definition at line 56 of file Core.cpp.
{
     _handle_game = _dl.loadLib(gamePath);
     _game = _dl.getSymbol<IGame>(_handle_game, "entryPoint");
 }
References _dl, _game, _handle_game, Arcade::DLLoader::getSymbol(), and Arcade::DLLoader::loadLib().
Referenced by launchGame().
setGraphicalLib()
void Core::setGraphicalLib (const std::string & graphicalPath)
Set the Graphical Lib object.
Parameters
graphicalPath Path to the graphical library
Definition at line 66 of file Core.cpp.
{
     _handle_graphical = _dl.loadLib(graphicalPath);
     _graphical = _dl.getSymbol<IGraphical>(_handle_graphical, "entryPoint");
 }
References _dl, _graphical, _handle_graphical, Arcade::DLLoader::getSymbol(), and Arcade::DLLoader::loadLib().
Referenced by displayMenu(), launchGame(), and switchLibs().
switchLibs()
void Core::switchLibs (std::vector< std::string > graphics, bool Direction)
Switch between the graphical libraries.
Parameters
graphics Vector of graphical libraries
Direction Direction of the switch (Previous or next)
Definition at line 182 of file Core.cpp.
{
     _graphical->destroyWindow();
     if (Direction)
         _selectedGraphicsIndex = (_selectedGraphicsIndex + 1) % graphics.size();
     else
         _selectedGraphicsIndex = (_selectedGraphicsIndex + graphics.size() - 1) % graphics.size();
     setGraphicalLib(graphics[_selectedGraphicsIndex]);
     _graphical->createWindow(WIDTH, HEIGHT, TITLE);
     _game->init(_graphical, _playerName);
 }
References _game, _graphical, _playerName, _selectedGraphicsIndex, IGraphical::createWindow(), IGraphical::destroyWindow(), HEIGHT, IGame::init(), setGraphicalLib(), TITLE, and WIDTH.
Referenced by getInputs().
Field Documentation
_dl
DLLoader Arcade::Core::_dl private
Definition at line 76 of file Core.hpp.
Referenced by Core(), setGameLib(), setGraphicalLib(), and ~Core().
_game
IGame* Arcade::Core::_game = nullptr private
Definition at line 69 of file Core.hpp.
Referenced by gameLoop(), launchGame(), setGameLib(), and switchLibs().
_gameStarted
bool Arcade::Core::_gameStarted = false private
Definition at line 80 of file Core.hpp.
Referenced by drawTextMenu(), gameLoop(), getInputs(), and launchGame().
_graphical
IGraphical* Arcade::Core::_graphical = nullptr private
Definition at line 74 of file Core.hpp.
Referenced by displayMenu(), drawTextMenu(), getInputs(), launchGame(), setGraphicalLib(), and switchLibs().
_handle_game
void* Arcade::Core::_handle_game = nullptr private
Definition at line 68 of file Core.hpp.
Referenced by Core(), setGameLib(), and ~Core().
_handle_graphical
void* Arcade::Core::_handle_graphical = nullptr private
Definition at line 73 of file Core.hpp.
Referenced by Core(), setGraphicalLib(), and ~Core().
_isInGame
bool Arcade::Core::_isInGame = false private
Definition at line 79 of file Core.hpp.
Referenced by drawTextMenu(), gameLoop(), and launchGame().
_playerName
std::string Arcade::Core::_playerName = "Player" private
Definition at line 72 of file Core.hpp.
Referenced by Core(), drawTextMenu(), launchGame(), and switchLibs().
_selectedGameIndex
int Arcade::Core::_selectedGameIndex = 0 private
Definition at line 81 of file Core.hpp.
Referenced by drawTextMenu(), getInputs(), and launchGame().
_selectedGraphicsIndex
int Arcade::Core::_selectedGraphicsIndex = 0 private
Definition at line 82 of file Core.hpp.
Referenced by drawTextMenu(), getInputs(), launchGame(), and switchLibs().
The documentation for this class was generated from the following files:
core/Core.hpp
core/Core.cpp