Arcade: graphicals/nCurses/nCurses.cpp File Reference
nCurses.cpp File Reference
#include "nCurses.hpp"
Functions
int enumToColor (Color color)
Function Documentation
enumToColor()
int enumToColor (Color color)
Definition at line 10 of file nCurses.cpp.
{
     switch (color) {
         case Color::RED:
             return 1;
         case Color::GREEN:
             return 2;
         case Color::YELLOW:
             return 3;
         case Color::BLUE:
             return 4;
         case Color::MAGENTA:
             return 5;
         case Color::CYAN:
             return 6;
         case Color::WHITE:
             return 7;
         default:
             return 0;
     }
 }
References BLUE, CYAN, GREEN, MAGENTA, RED, WHITE, and YELLOW.
Referenced by nCurses::drawCircle(), nCurses::drawRectangle(), and nCurses::drawText().