version: '3'
services:
  server:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./back:/app
    environment:
      NODE_ENV: development
  client:
    build:
      context: ./trombarea
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
