##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## Makefile
##

all:
	@make -C corewar/ --no-print-directory
	@make -C asm/ --no-print-directory
clean:
	@make clean -C corewar/ --no-print-directory
	@make clean -C asm/ --no-print-directory

fclean:	clean
	@make fclean -C corewar/ --no-print-directory
	@make fclean -C asm/ --no-print-directory

re:	fclean all
