##
## EPITECH PROJECT, 2022
## B-OOP-400-MPL-4-1-arcade-loic.tisseyre
## File description:
## Makefile
##

.SILENT:

all:
	@make -C ./Snake
	@make -C ./Nibbler

clean:
	@make clean -C ./Snake
	@make clean -C ./Nibbler

fclean: clean
	@make fclean -C ./Snake
	@make fclean -C ./Nibbler

re: fclean all